# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

python:
  - "2.7"

install:
  - pip install -e .
  - pip install codecov

script:
  - coverage run setup.py test
  - coverage report -m

after_script:
  codecov
