# After changing this file, check it on: http://lint.travis-ci.org/
language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - pypy
  - pypy3

before_install:
  # Check default Python version installed.
  - python --version

install:
  - pip install -e .[tests]

before_script:
  - pip install codecov

script:
  - coverage run ./setup.py test
  - coverage report -m
  - pep8

after_script:
  - codecov
